{{- if .Values.selfSignedCertificate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selfSignedCertName" . }}
type: Opaque
data:
  crt: {{ .Values.selfSignedCertificate.certificate | b64enc }}
{{- end }}