{{ if .Values.controlThePayloadConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  controlThePayloadConfig: |-
    {{- .Values.controlThePayloadConfig | nindent 4 }}
{{- end }}