{{ if .Values.controlThePayloadConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "port-agent.fullname" . }}
data:
  controlThePayloadConfig: |-
    {{- .Values.controlThePayloadConfig | nindent 4 }}
{{- end }}