apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "port-agent.fullname" . }}
  labels:
    {{- include "port-agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "port-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "port-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.selfSignedCertificate.enabled }}
          command: [ "sh", "-c", "update-ca-certificates && python3 main.py" ]
          {{- end }}
          env:
            {{- if .Values.selfSignedCertificate.enabled }}
            {{/* Used for requests library in python */}}
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            {{- end }}
            {{- include "port-agent.envVariables" . | indent 12 }}
          {{- if eq .Values.secret.useExistingSecret true }}
          envFrom:
            - secretRef:
                name: {{ include "port-agent.secretName" . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.controlThePayloadConfig }}
            - mountPath: /app/control_the_payload_config.json
              name: {{ include "port-agent.fullname" . }}
              subPath: controlThePayloadConfig
            {{- end }}
          {{- if .Values.selfSignedCertificate.enabled }}
            - name: certificates
              mountPath: /usr/local/share/ca-certificates/cert.crt
              subPath: cert.crt
              readOnly: true
          {{- end }}
      volumes:
        {{- if .Values.controlThePayloadConfig }}
        - name: {{ include "port-agent.fullname" . }}
          configMap:
            name: {{ include "port-agent.fullname" . }}
        {{- end }}
        {{- if .Values.selfSignedCertificate.enabled }}
        - name: certificates
          projected:
            sources:
              - secret:
                  name: {{ include "port-ocean.selfSignedCertName" . }}
                  items:
                    - key: crt
                      path: cert.crt
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
