apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-agent.secretName" . }}
  labels:
    {{- include "port-agent.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}