nameOverride: ""
fullnameOverride: ""

port:
  clientId: 
    type: secret
    key: PORT_CLIENT_ID
    value: ""
  clientSecret: 
    type: secret
    key: PORT_CLIENT_SECRET
    value: ""
  baseUrl: https://api.getport.io/v1

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: true
  type: ClusterIP
  port: 8000
  
ingress:
  enabled: false
  annotations: {}
  host: null
  
integration:
  identifier: ""
  version: ""
  type: ""
  config: {}
  triggerChannel:
    type: "KAFKA"