resyncInterval: 0
stateKey: ""
deleteDependents: false
createMissingRelatedEntities: false
portBaseUrl: https://api.getport.io
verbosity: 0

image:
  repository: ghcr.io/port-labs/port-k8s-exporter
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secret:
  annotations: {}
  name: ""
  secrets:
    portClientId: ""
    portClientSecret: ""
  # secret.useExistingSecret -- Enable this if you wish to create your own secret with credentials.
  useExistingSecret: false

configMap:
  annotations: {}
  config:
  name: ""
  # configMap.create -- Disable to specify your own configmap to be used.
  create: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

clusterRole:
  annotations: {}
  name: ""
  apiGroups:
    - "'*'"
  resources:
    - "'*'"

clusterRoleBinding:
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: []
  # - name: "KUBECONFIG"
  #   value: /tmp/.kube/config

extraObjects: []
# - apiVersion: v1
#   kind: Secret
#   metadata:
#     name: kubeconfig
#   type: Opaque
#   stringData:

extraVolumes: []
  # - name: kubeconfig
  #   secret:
  #     secretName: kubeconfig

extraVolumeMounts: []
  # - name: kubeconfig
  #   mountPath: "/tmp/.kube"
