apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "port-k8s-exporter.fullname" . }}
  labels:
    {{- include "port-k8s-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "port-k8s-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "port-k8s-exporter.selectorLabels" . | nindent 8 }}
        config-hash: {{ .Values.configMap.config | toYaml | sha256sum | trunc 32 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "port-k8s-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            - -config
            - /config/config.yaml
          envFrom:
            - secretRef:
                name: {{ include "port-k8s-exporter.secretName" . }}
          volumeMounts:
            - name: config-volume
              mountPath: "/config"
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "port-k8s-exporter.configMapName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
