{{- if and .Values.selfSignedCertificate.enabled (eq false .Values.selfSignedCertificate.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-ocean.selfSignedCertName" . }}
type: Opaque
data:
  crt: {{ .Values.selfSignedCertificate.certificate | b64enc }}
{{- end }}
