{{- if .Values.integration.selfSignedCertificate.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-ocean.selfSignedCertName" . }}
type: Opaque
data:
  crt: {{ .Values.integration.selfSignedCertificate.certificate | b64enc }}
{{- end }}