apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "port-ocean.configMapName" . }}
data:
  config.yaml: |-
    port:
      {{- range $key, $value := .Values.port }}
      {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
      {{- end}}
    triggerChannel: 
      {{- range $key, $value := .Values.integration.triggerChannel }}
      {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
      {{- end}}
    integration:
      identifier: {{ include "port-ocean.getOceanConfigYamlValue" .Values.integration.identifier }}
      type: {{ include "port-ocean.getOceanConfigYamlValue" .Values.integration.type }}
      config:
        {{- range $key, $value := .Values.integration.config }}
        {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
        {{- end}}