{{- range .Values.integrations }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "port-ocean.configMapName" . }}
data:
  config.yaml: |-
    port:
      {{- range $key, $value := $.Values.port }}
      {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
      {{- end}}
    triggerChannel: 
      {{- range $key, $value := .triggerChannel }}
      {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
      {{- end}}
    integration:
      identifier: {{ include "port-ocean.getOceanConfigYamlValue" .identifier }}
      type: {{ include "port-ocean.getOceanConfigYamlValue" .type }}
      config:
        {{- range $key, $value := .config }}
        {{ $key }}: {{ include "port-ocean.getOceanConfigYamlValue" $value }}
        {{- end}}
{{- end}}