apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "port-ocean.deploymentName" . }}
  labels:
    {{- include "port-ocean.labels" . | nindent 8 }}
spec:
  strategy:
    type: {{ .Values.rolloutStrategy | default "Recreate" }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "port-ocean.deploymentName" . }}
      {{- include "port-ocean.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "port-ocean.deploymentName" .}}
        {{- include "port-ocean.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      securityContext:
        {{- if .Values.podSecurityContext }}
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        {{- end }}
      containers:
      - name: {{ include "port-ocean.containerName" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.imageRegistry }}/port-ocean-{{ .Values.integration.type }}:{{ .Values.integration.version | default "latest" }}
        {{- if .Values.service.enabled }}
        securityContext:
        {{- if .Values.containerSecurityContext }}
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        {{- end }}
        resources:
        {{- if .Values.resources }}
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{.Values.service.port}}
          protocol: TCP
        {{- end }}
        env:
        {{- if .Values.selfSignedCertificate.enabled }}
          - name: SSL_CERT_FILE
            value: /etc/ssl/certs/ca-certificates.crt
        {{- end }}
        {{- with .Values.extraEnv }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "port-ocean.configMapName" . }}
          - secretRef:
              name: {{ include "port-ocean.secretName" . }}
        volumeMounts:
        {{- if .Values.selfSignedCertificate.enabled }}
          - name: certificates
            mountPath: /usr/local/share/ca-certificates/cert.crt
            subPath: cert.crt
            readOnly: true
        {{- end }}
      volumes:
        {{- if .Values.selfSignedCertificate.enabled }}
        - name: certificates
          projected:
            sources:
              - secret:
                  name: {{ include "port-ocean.selfSignedCertName" . }}
                  items:
                    - key: crt
                      path: cert.crt
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

