apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "port-ocean.deploymentName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "port-ocean.deploymentName" . }}
  template:
    metadata:
      labels:
        app: {{ include "port-ocean.deploymentName" .}}
    spec:
      containers:
      - name: {{ include "port-ocean.containerName" . }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- if .Values.integration.selfSignedCertificate.enabled }}
        command: ["sh", "-c", "update-ca-certificates && ocean sail"]
        {{- end }}
        image: ghcr.io/port-labs/port-ocean-{{ .Values.integration.type }}:{{ .Values.integration.version | default "latest" }}
        {{- if .Values.service.enabled }}
        ports:
        - containerPort: {{.Values.service.port}}
          protocol: TCP
        {{- end }}
        {{- if .Values.integration.selfSignedCertificate.enabled }}
        env:
          - name: SSL_CERT_FILE
            value: /etc/ssl/certs/ca-certificates.crt
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ include "port-ocean.configMapName" . }}
          - secretRef:
              name: {{ include "port-ocean.secretName" . }}
        volumeMounts:
        {{- if .Values.integration.selfSignedCertificate.enabled }}
          - name: certificates
            mountPath: /usr/local/share/ca-certificates/cert.crt
            subPath: cert.crt
            readOnly: true
        {{- end }}
      volumes:
        {{- if .Values.integration.selfSignedCertificate.enabled }}
        - name: certificates
          projected:
            sources:
              - secret:
                  name: {{ include "port-ocean.selfSignedCertName" . }}
                  items:
                    - key: crt
                      path: cert.crt
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}

