apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-ocean.secretName" . }}
  labels:
    {{- include "port-ocean.labels" $ | nindent 4 }}
type: opaque
data: 
  PORT_CLIENT_ID: {{ .Values.port.clientId | b64enc | quote }}
  PORT_CLIENT_SECRET: {{ .Values.port.clientSecret | b64enc | quote }}
  {{- if .Values.integration.secrets }}
  {{- range $key, $value := .Values.integration.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
