apiVersion: v1
kind: Secret
metadata:
  name: {{ include "port-ocean.secretName" . }}
  labels:
    {{- include "port-ocean.labels" $ | nindent 4 }}
type: opaque
data: 
  {{- range $key, $value := .Values.port }}
  {{- include "port-ocean.secretValue" $value }}
  {{- end}}
  {{- range $key, $value := .Values.integration.triggerChannel }}
  {{- include "port-ocean.secretValue" $value }}
  {{- end}}
  {{- include "port-ocean.secretValue" .Values.integration.identifier }} 
  {{- include "port-ocean.secretValue" .Values.integration.type }}
  {{- range $key, $value := .Values.integration.config }}
  {{- include "port-ocean.secretValue" $value }}
  {{- end}}
